#!/usr/bin/env python2

import time
from futuredash.dzen import Dzen2, Vol, Date, Battery, Wifi, Network, I3Workspaces

if __name__ == "__main__":
    dzen = Dzen2({"bg": "#191F27", "fg": "#ECF1F3", "alignment": "l"})
    p = 350
    while True:
        p -=1
        dzen\
        .clear()\
        .set_widget(Wifi())\
        .text("  ")\
        .set_widget(Network())\
        .text("  ")\
        .set_widget(Vol())\
        .text("  ")\
        .set_widget(Date())\
        .text("  ")\
        .position("+350")\
        .text("  ")\
        .set_widget(I3Workspaces())\
        .send()
